import logging
logger = logging.getLogger(__name__)

# Conversation states
CHOOSING_REPORT_TYPE = 0
CHOOSING_LOCATION = 1  # New state for location selection
COLLECTING_DATA = 2
PHOTO = 3
SEARCHING_REPORT = 4
SEND_MESSAGE = 5
DESCRIPTION = 6
SEARCH_MISSING_PERSON = 7
SEND_MESSAGE_TO_REPORTER = 8
SELECT_URGENCY = 9  # Added missing state for urgency selection
UPDATE_REPORT_STATUS = 10  # New state for updating report status
CHOOSE_STATUS = 11  # New state for choosing the status
COLLECT_NAME = 30
COLLECT_AGE = 31
COLLECT_GENDER = 32
COLLECT_DESCRIPTION = 33
COLLECT_LAST_SEEN_LOCATION = 34
COLLECT_LAST_SEEN_TIME = 35
COLLECT_MEDICAL_INFO = 36
COLLECT_CONTACT_INFO = 37
COLLECT_EXACT_LOCATION = 38  # For map pin/coordinates
COLLECT_PEOPLE_COUNT = 39  # For rescue requests
COLLECT_INJURIES = 40  # For medical needs
COLLECT_BUILDING_CONDITION = 41  # For trapped people
COLLECT_RELATIONSHIP = 42  
COLLECT_HELP_TYPE = 43  # This is the one causing the error
COLLECT_RESOURCES = 44
COLLECT_AVAILABILITY = 45
COLLECT_CURRENT_LOCATION = 46  # For missing person reports
COLLECT_CUSTOM_COORDINATES = 47

__all__ = [
    'CHOOSING_REPORT_TYPE', 'COLLECTING_DATA', 'PHOTO',
    'SEARCHING_REPORT', 'SEND_MESSAGE', 'DESCRIPTION',
    'SEARCH_MISSING_PERSON', 'SEND_MESSAGE_TO_REPORTER',
    'CHOOSING_LOCATION', 'SELECT_URGENCY', 'UPDATE_REPORT_STATUS', 'CHOOSE_STATUS',
    'COLLECT_NAME', 'COLLECT_AGE', 'COLLECT_GENDER', 'COLLECT_DESCRIPTION', 
    'COLLECT_LAST_SEEN_LOCATION', 'COLLECT_LAST_SEEN_TIME', 'COLLECT_MEDICAL_INFO',
    'COLLECT_CONTACT_INFO', 'COLLECT_EXACT_LOCATION', 'COLLECT_PEOPLE_COUNT',
    'COLLECT_INJURIES', 'COLLECT_BUILDING_CONDITION', 'COLLECT_RELATIONSHIP', 
    'COLLECT_CURRENT_LOCATION', 'COLLECT_HELP_TYPE', 'COLLECT_RESOURCES', 'COLLECT_AVAILABILITY', 'COLLECT_CURRENT_LOCATION',
    'COLLECT_CUSTOM_COORDINATES',
]
# Check state definitions
logger.info(f"CHOOSING_REPORT_TYPE: {CHOOSING_REPORT_TYPE}")
logger.info(f"CHOOSING_LOCATION: {CHOOSING_LOCATION}")
logger.info(f"COLLECTING_DATA: {COLLECTING_DATA}")
logger.info(f"PHOTO: {PHOTO}")
logger.info(f"SEARCHING_REPORT: {SEARCHING_REPORT}")
logger.info(f"SEND_MESSAGE: {SEND_MESSAGE}")
logger.info(f"DESCRIPTION: {DESCRIPTION}")
logger.info(f"SEARCH_MISSING_PERSON: {SEARCH_MISSING_PERSON}")
logger.info(f"SEND_MESSAGE_TO_REPORTER: {SEND_MESSAGE_TO_REPORTER}")
logger.info(f"SELECT_URGENCY: {SELECT_URGENCY}")
logger.info(f"UPDATE_REPORT_STATUS: {UPDATE_REPORT_STATUS}")
logger.info(f"CHOOSE_STATUS: {CHOOSE_STATUS}")
